= Git Metafile
Jakub Jirutka <https://github.com/jirutka[@jirutka]>
//custom
:name: git-metafile
:version: 0.2.1
:gh-name: jirutka/{name}
:gh-branch: master
:releases-uri: https://github.com/{gh-name}/releases/download/v{version}

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg[CI Status, link=https://github.com/{gh-name}/actions?query=workflow%3A%22CI%22]
endif::env-github[]

A simple tool for storing and restoring files metadata (mode, owner, group) in a git repository.
It's designed especially for versioning /etc.

// TODO: Add more information.


== Installation

=== Using pre-built binaries

. Install git (use your system’s package manager).

. Download and extract release tarball for your OS and CPU architecture (pick the right link from the table below):
+
[source, sh, subs="verbatim, attributes"]
----
curl -sSLO {releases-uri}/{name}-{version}-x86_64-unknown-linux-musl.tar.gz
curl -sSL {releases-uri}/checksums.txt | sha256sum -c --ignore-missing
tar -xzf {name}-{version}-*.tar.gz
----

. Install `{name}` somewhere on your `PATH`, e.g. `/usr/local/bin`:
+
[source, sh, subs="verbatim, attributes"]
install -m 755 {name}-{version}-*/{name} /usr/local/bin/


==== Release tarballs for the latest version

[cols="10,30,10,50", width="100%"]
|===
| OS | Architecture | libc | File

.6+| Linux
.2+| x86_64
| musl*
| {releases-uri}/{name}-{version}-x86_64-unknown-linux-musl.tar.gz[{name}-{version}-x86_64-unknown-linux-musl.tar.gz]

| glibc
| {releases-uri}/{name}-{version}-x86_64-unknown-linux-gnu.tar.gz[{name}-{version}-x86_64-unknown-linux-gnu.tar.gz]

| aarch64 (ARM 64bit)
| musl*
| {releases-uri}/{name}-{version}-aarch64-unknown-linux-musl.tar.gz[{name}-{version}-aarch64-unknown-linux-musl.tar.gz]

| armv7 (ARM 32bit)
| musl*
| {releases-uri}/{name}-{version}-armv7-unknown-linux-musleabihf.tar.gz[{name}-{version}-armv7-unknown-linux-musleabihf.tar.gz]

| ppc64le (PowerPC LE)
| glibc
| {releases-uri}/{name}-{version}-powerpc64le-unknown-linux-gnu.tar.gz[{name}-{version}-powerpc64le-unknown-linux-gnu.tar.gz]

| riscv64gc (RISC-V)
| glibc
| {releases-uri}/{name}-{version}-riscv64gc-unknown-linux-gnu.tar.gz[{name}-{version}-riscv64gc-unknown-linux-gnu.tar.gz]

| macOS
| x86_64 (Intel 64bit)
|
| {releases-uri}/{name}-{version}-x86_64-apple-darwin.tar.gz[{name}-{version}-x86_64-apple-darwin.tar.gz]
|===

_* musl binaries are statically linked with http://www.musl-libc.org/[musl libc], so they work on every Linux system (distro) regardless of used libc._


=== On Alpine Linux

Install package {name} from the Alpine’s community repository:

[source, sh, subs="attributes"]
apk add {name}


=== From source tarball

. Install git (use your system’s package manager).

. Download and unpack the tarball:
+
[source, sh, subs="+attributes"]
----
wget https://github.com/{gh-name}/archive/v{version}/{name}-{version}.tar.gz
tar -xzf {name}-{version}.tar.gz
cd {name}-{version}
----

. Build {name} using cargo:
+
[source, sh]
cargo build --release --locked

. Grab the binary from `target/release/{name}` and install it somewhere on your `PATH`, e.g. `/usr/local/bin`:
+
[source, sh, subs="+attributes"]
install -D -m755 target/release/{name} -t /usr/local/bin/


== How to use

To automatically record files attributes on every commit and restore them on every checkout, set up git hooks:

[source, sh]
----
cat >> .git/hooks/pre-commit <<EOF
#!/bin/sh

git-metafile save && git add .metafile
EOF

chmod +x .git/hooks/pre-commit

cat >> .git/hooks/post-checkout <<EOF
#!/bin/sh

git-metafile apply
EOF

chmod +x .git/hooks/post-checkout
ln -s post-checkout .git/hooks/post-rewrite
----

This should work for all basic operations, so you don’t need to think about it anymore.
However, you have to be careful when rebasing – no hook is run when git checkouts files during rebase and _before_ committing changes done in rebase mode!

To record changes or restore files attributes manually, you can run `git metafile save` or `git metafile apply` respectively.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
