= Git Metafile
Jakub Jirutka <https://github.com/jirutka[@jirutka]>
//custom
:name: git-metafile
:version: 0.2.0
:gh-name: jirutka/{name}
:gh-branch: master

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}["Build Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]

A simple tool for storing and restoring files metadata (mode, owner, group) in a git repository.
It's designed especially for versioning /etc.

TODO


== Installation

=== Using pre-built binaries

. Install git (use your system’s package manager).

. Download and extract {name} tarball for your OS and platform (pick the right link from the table below):
+
[source, sh, subs="verbatim, attributes"]
----
wget https://github.com/{gh-name}/releases/download/v{version}/{name}-{version}-x86_64-unknown-linux-musl.tar.gz
tar -xzf {name}-{version}-*.tar.gz
----

. Install `bin/{name}` somewhere on your `PATH`, e.g. `/usr/local/bin`:
+
[source, sh, subs="verbatim, attributes"]
cp {name}-{version}-*/bin/{name} /usr/local/bin/


.Release tarballs for version {version}
[cols="2", width="100%"]
|===
| Linux (static binary)
| https://github.com/{gh-name}/releases/download/v{version}/{name}-{version}-x86_64-unknown-linux-musl.tar.gz[x86_64] (64 bit)

| Linux (glibc)
| https://github.com/{gh-name}/releases/download/v{version}/{name}-{version}-x86_64-unknown-linux-gnu.tar.gz[x86_64] (64 bit)

| OS X
| https://github.com/{gh-name}/releases/download/v{version}/{name}-{version}-x86_64-apple-darwin.tar.gz[x86_64] (64 bit)
|===

Note: Static binaries (statically linked with http://www.musl-libc.org/[musl libc]) don’t have dynamic dependencies and so should work on any Linux system.


=== From sources

. Install git (use your system’s package manager).

. Clone this repository and jump in:
+
[source, sh, subs="verbatim, attributes"]
----
git clone https://github.com/{gh-name}.git
cd {name}
----

. Build the package using cargo:
+
    cargo build --release

. Grab the binary from `target/release/{name}` and install it somewhere on your `PATH`, e.g. `/usr/local/bin`:
+
[source, sh, subs="verbatim, attributes"]
cp target/release/{name} /usr/local/bin


== How to use

To automatically record files attributes on every commit and restore them on every checkout, set up git hooks:

[source, sh]
----
cat >> .git/hooks/pre-commit <<EOF
#!/bin/sh

git-metafile save && git add .metafile
EOF

chmod +x .git/hooks/pre-commit

cat >> .git/hooks/post-checkout <<EOF
#!/bin/sh

git-metafile apply
EOF

chmod +x .git/hooks/post-checkout
ln -s post-checkout .git/hooks/post-rewrite
----

This should work for all basic operations, so you don’t need to think about it anymore.
However, you have to be careful when rebasing – no hook is run when git checkouts files during rebase and _before_ committing changes done in rebase mode!

To record changes or restore files attributes manually, you can run `git metafile save` or `git metafile apply` respectively.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
