#!/bin/bash
# vim: set ts=4:
set -eu

source "$(dirname $0)/utils.sh"


host-triplet() {
	case "$TRAVIS_OS_NAME" in
		linux) echo "$(uname -m)-unknown-linux-gnu" ;;
		osx) echo "$(uname -m)-apple-darwin" ;;
		*) die "Unknown OS: $TRAVIS_OS_NAME" ;;
	esac
}

target-triplet() {
	case "$TRAVIS_OS_NAME" in
		linux) echo "$TARGET_CPU-unknown-linux-${TARGET_OS/host/gnu}" ;;
		osx) echo "$TARGET_CPU-apple-darwin" ;;
		*) die "Unknown OS: $TRAVIS_OS_NAME" ;;
	esac
}


case "$1" in
	host-triplet | target-triplet)
		eval "$1"
	;;
	*) die "Unknown command: $1" ;;
esac
