#!/bin/bash
# vim: set ts=4:
set -eu -o pipefail

echo -e '\n==> Uninstalling system-provided Rust...'
sh ~/rust/lib/rustlib/uninstall.sh

echo -e '\n==> Installing rustup...'
curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=$TRAVIS_RUST_VERSION

if [ "$HOST" != "$TARGET" ]; then
	rustup target add "$TARGET"
fi

rustup show
