#!/bin/bash
# vim: set ts=4:
set -eu -o pipefail

cd "$(dirname $0)/.."
source script/utils.sh


einfo 'Installing rustup...'

curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=$TRAVIS_RUST_VERSION

if [ "$HOST" != "$TARGET" ]; then
	rustup target add "$TARGET"
fi

rustup show
