name: CI
on:
  - push
  - pull_request

env:
  CRATE_NAME: git-metafile

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run clippy linter
        run: cargo clippy

      - name: Run rustfmt check (ignore any errors)
        run: cargo fmt -- --check || true

  test:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        rust:
          - stable
          - beta
          - nightly
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    env:
      CARGO_TERM_VERBOSE: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.rust }} for ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.rust }}

      - name: Build binary
        run: cargo build --target ${{ matrix.target }}

      - name: Run tests
        if: matrix.target != 'aarch64-apple-darwin'
        run: cargo test --target ${{ matrix.target }}

      - name: Upload binaries to artifacts
        if: matrix.rust == 'stable'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/${{ env.CRATE_NAME }}
          if-no-files-found: error
